networks:
  app-tier:
    driver: bridge

services:
  # listens to mqtt packets and saves to database
  meshtastic-mqtt:
    container_name: meshtastic-mqtt
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /app/docker/mqtt.sh
    env_file:
      - .env.local
    networks:
      - app-tier

  # runs the web map ui
  meshtastic-map:
    container_name: meshtastic-map
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /app/docker/map.sh
    ports:
      - 8080:8080/tcp
    env_file:
      - .env.local
    networks:
      - app-tier

  # runs the database to store everything from mqtt
  database:
    container_name: database
    image: bitnami/mariadb:10.11
    ports:
      - 3306:3306/tcp
    env_file:
      - .env.local
    volumes:
      - database_data:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      start_interval: 5s
    networks:
      - app-tier

volumes:
  database_data:
